#lang racket
(define (square x) (* x x))
(define (sum-of-square-of-biggest a b c)
  (if (and (>= a c) 
           (>= b c))
      (+ (square a) (square b))
      (+ (if (>= a b) 
             (square a) 
             (square b)) 
         (square c))
      )
  )
(= (sum-of-square-of-biggest 3 2 3) 18)
(= (sum-of-square-of-biggest 1 2 3) 13)
(= (sum-of-square-of-biggest 3 2 1) 13)
(= (sum-of-square-of-biggest 1 3 2) 13)
(= (sum-of-square-of-biggest 3 1 1) 10)
(= (sum-of-square-of-biggest 2 2 2) 8)
(= (sum-of-square-of-biggest 0 0 2) 4)
(= (sum-of-square-of-biggest 1 -2 -2) 5)
